language: r

dist: bionic

# need sudo
sudo: true

# cache packages because devtools is a beast
cache: packages

# Be strict when checking our package
warnings_are_errors: true

# don't build the vignette
r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --ignore-vignettes --as-cran"

# System dependencies
#apt_packages:
# - libmpfr6
# - libmpfr-dev
 
# Binaries from Michael Rutter's ppa
r_binary_packages:
 - rmpfr
 - testthat
 - zoo
 - xts
 - plm

# Done via install.packages
#r_packages:

# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
r_github_packages:  
 - braverock/PerformanceAnalytics
 - braverock/FactorAnalytics
 
#  - r-lib/covr

# after_success:
#   - travis_wait 30 Rscript -e 'covr::codecov()'
